#!/bin/bash

MSG="$1"

if ! grep -qE "\(*(refactor|feat|fix)\)\s.{20,}" "$MSG";then
    cat "$MSG"
    echo "Your commit message must start with (feat|refactor|fix), e.g. (fix) this is a description"
    exit 1
fi